site_name: Technical Writing Portfolio

site_description: Docs-as-Code portfolio showcasing enterprise SaaS documentation

site_url: https://ajinanga16-blip.github.io/tech-writer-portfolio/
use_directory_urls: true


extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js
extra:
  mermaid:
    theme: default
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.progressbar
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.arithmatex
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md

  - Release Notes:
      - Overview: release-notes/index.md
      - "2026.1": release-notes/v2026-1.md
      - "2025.12": release-notes/v2025-12.md
      - "2025.11": release-notes/v2025-11.md
      - "2025.10": release-notes/v2025-10.md
      - "2025.9": release-notes/v2025-9.md

  - What's New:
      - Overview: whats-new/index.md
      - "2026.1": whats-new/2026-1.md
      - "2025.12": whats-new/2025-12.md
      - "2025.11": whats-new/2025-11.md
      - "2025.10": whats-new/2025-10.md
      - "2025.9": whats-new/2025-9.md

  - User Guides:
      - Overview: user-guides/index.md
      - Forecasting Overview: user-guides/forecasting-overview.md
      - Build a Forecast Scenario: user-guides/build-forecast-scenario.md
      - Review and Submit a Forecast: user-guides/review-submit-forecast.md



  - How-To Guides:
      - Overview: how-to/index.md
      - Create a Budget: how-to/create-budget.md

  - FAQs:
      - Overview: faqs/index.md

  - Troubleshooting:
      - Overview: troubleshooting/index.md

  - UX Copy:
      - Overview: ux-copy/index.md
      - Modals: ux-copy/modals.md

  - Release Highlights:
      - Overview: release-highlights/index.md
  - Documentation Strategy:
      - Strategy & Metrics: documentation-strategy/index.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.progressbar
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.arithmatex
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

